import { test, expect } from '@playwright/test';
test.beforeEach(async ({ page }) => { await page.addInitScript(() => { sessionStorage.setItem('announcementDismissed', 'true'); }); });
test('purchase flow, options, quantity, persistence, checkout', async ({ page, context }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/shop');
  await expect(page.getByRole('heading', { name: 'Shop PrintFlow Studio' })).toBeVisible();
  await page.getByRole('link', { name: 'Test PrintFlow Tee', exact: true }).click();
  await page.getByLabel('Size', { exact: true }).selectOption('M');
  await page.getByLabel('Color', { exact: true }).selectOption('White');
  await expect(page.locator('.shop-product-details .shop-price')).toContainText('$30.99');
  await page.getByRole('button', { name: 'View image 2' }).click();
  await expect(page.locator('.shop-product-image .shop-image-wrap img')).toHaveAttribute('alt', 'Test tee artwork');
  await page.getByRole('button', { name: 'Add to Cart', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Added to your cart.' })).toBeVisible();
  await page.getByRole('link', { name: 'View cart', exact: true }).click();
  await expect(page.locator('.shop-cart-line')).toContainText('Size: M · Color: White');
  await page.getByRole('button', { name: 'Increase quantity of Test PrintFlow Tee' }).click();
  await expect(page.getByRole('heading', { name: 'Subtotal $61.98' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Subtotal $61.98' })).toBeVisible();
  const cookies = await context.cookies(); expect(cookies.find(c => c.name === 'pf_shopify_cart')?.httpOnly).toBe(true);
  expect(await page.evaluate(() => document.cookie)).not.toContain('pf_shopify_cart');
  await page.getByRole('button', { name: 'Decrease quantity of Test PrintFlow Tee' }).click();
  await expect(page.getByRole('heading', { name: 'Subtotal $30.99' })).toBeVisible();
  await page.getByLabel('Quantity for Test PrintFlow Tee').selectOption('3');
  await expect(page.getByRole('heading', { name: 'Subtotal $92.97' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: `test-results/cart-${test.info().project.name}.png`, fullPage: true });
  await page.route('https://theprintflowstudio.myshopify.com/checkouts/test', route => route.fulfill({ body: '<h1>Shopify checkout test destination</h1>', contentType: 'text/html' }));
  await page.getByRole('button', { name: 'Secure Checkout' }).click();
  await expect(page).toHaveURL('https://theprintflowstudio.myshopify.com/checkouts/test');
  expect(errors).toEqual([]);
});
test('sold-out variant and product, single variant, no image, remove', async ({ page }) => {
  await page.goto('/shop/test-tee');
  await page.getByLabel('Color', { exact: true }).selectOption('White');
  await expect(page.getByRole('button', { name: 'Unavailable', exact: true })).toBeDisabled();
  await page.goto('/shop/soldout');
  await expect(page.getByRole('button', { name: 'Unavailable', exact: true })).toBeDisabled();
  await page.goto('/shop/single');
  await expect(page.getByText('Image coming soon')).toBeVisible();
  await expect(page.getByLabel('Size', { exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Add to Cart', exact: true }).click();
  await page.getByRole('link', { name: 'View cart', exact: true }).click();
  await page.getByRole('button', { name: 'Remove', exact: true }).click();
  await expect(page.getByText('Your cart is empty.')).toBeVisible();
});
test('invalid product, empty/error states, transfer catalog, responsive grid', async ({ page }) => {
  await page.goto('/shop/missing'); await expect(page.getByRole('alert')).toContainText('Product not found.');
  await page.goto('/dtf-transfers'); await expect(page.getByRole('heading', { name: 'Test PrintFlow Tee' })).toBeVisible();
  await page.getByRole('link', { name: 'Test PrintFlow Tee', exact: true }).click(); await expect(page).toHaveURL(/\/shop\/test-tee$/);
  await page.goto('/shop'); await expect(page.locator('.shop-card')).toHaveCount(3);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: `test-results/shop-${test.info().project.name}.png`, fullPage: true });
  await page.route('**/api/commerce?resource=products', route => route.fulfill({ json: { nodes: [], pageInfo: { hasNextPage: false } } }));
  await page.reload(); await expect(page.getByRole('status')).toContainText('New designs are on the way');
  await page.route('**/api/commerce?resource=products', route => route.fulfill({ status: 503, json: { error: 'Our shop is temporarily unavailable. Please try again shortly.' } }));
  await page.reload(); await expect(page.getByRole('alert')).toContainText('temporarily unavailable');
});
