import { test, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/commerce.js';
import { getProduct, safeCheckout } from '../server/shopify.js';
import { metadata } from '../api/product-page.js';
const nativeFetch = global.fetch;
const baseEnv = { ...process.env };
let calls;
beforeEach(() => { process.env.SHOPIFY_STORE_DOMAIN = 'theprintflowstudio.myshopify.com'; process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN = 'private-test-token'; process.env.SITE_URL = 'https://www.printflowstudio.com'; calls = []; });
afterEach(() => { global.fetch = nativeFetch; process.env = { ...baseEnv }; });
function mock(...results) { global.fetch = async (url, options) => { calls.push({ url, ...options, body: JSON.parse(options.body) }); const result = results.shift(); if (result instanceof Error) throw result; return { ok: true, json: async () => result }; }; }
async function run({ method = 'GET', query = {}, body = {}, headers = {} } = {}) {
  const req = { method, query, body, headers: { origin: 'https://www.printflowstudio.com', 'content-type': 'application/json', ...headers }, socket: { remoteAddress: '127.0.0.1' } };
  const res = { code: 200, headers: {}, setHeader(k, v) { this.headers[k] = v; }, status(code) { this.code = code; return this; }, json(data) { this.body = data; return this; } };
  await handler(req, res); return res;
}
const m = { amount: '27.99', currencyCode: 'USD' };
const variant = { id: 'gid://shopify/ProductVariant/1', availableForSale: true, price: m, selectedOptions: [{ name: 'Size', value: 'M' }] };
const cart = { id: 'gid://shopify/Cart/abc?key=cart-secret', checkoutUrl: 'https://theprintflowstudio.myshopify.com/checkouts/abc', totalQuantity: 1, cost: { subtotalAmount: m }, lines: { nodes: [{ id: 'line-1', quantity: 1, merchandise: variant }] } };
const cookie = { cookie: `pf_shopify_cart=${encodeURIComponent(cart.id)}` };
const product = { handle: 'test-tee', title: '</title><script>attack</script>', description: 'Test', options: [{ name: 'Size', optionValues: [{ name: 'M' }] }], seo: {}, images: { nodes: [] }, variants: { nodes: [variant], pageInfo: { hasNextPage: false } } };
test('missing configuration is sanitized and not cached', async () => { delete process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN; const r = await run({ query: { resource: 'products' } }); assert.equal(r.code, 503); assert.match(r.body.error, /temporarily unavailable/); assert.equal(r.headers['Cache-Control'], 'private, no-store'); });
test('catalog uses Storefront publication and short caching with cursors', async () => { mock({ data: { products: { nodes: [product], pageInfo: { hasNextPage: true, endCursor: 'next' } } } }); const r = await run({ query: { resource: 'products', after: 'previous' } }); assert.equal(r.code, 200); assert.deepEqual(r.body.nodes[0].options, [{ name: 'Size', values: ['M'] }]); assert.equal(calls[0].body.variables.after, 'previous'); assert.equal(calls[0].headers['Shopify-Storefront-Private-Token'], 'private-test-token'); assert.match(r.headers['Cache-Control'], /s-maxage=60/); });
test('all variant pages are fetched', async () => { mock({ data: { product: { ...product, variants: { nodes: [variant], pageInfo: { hasNextPage: true, endCursor: 'page2' } } } } }, { data: { product: { ...product, variants: { nodes: [{ ...variant, id: 'second' }], pageInfo: { hasNextPage: false } } } } }); const p = await getProduct('test-tee'); assert.equal(p.variants.nodes.length, 2); assert.equal(calls[1].body.variables.after, 'page2'); });
test('invalid handle and missing product return 404', async () => { assert.equal((await run({ query: { resource: 'product', handle: '../secret' } })).code, 404); mock({ data: { product: null } }); assert.equal((await run({ query: { resource: 'product', handle: 'missing' } })).code, 404); });
test('cart creation stores secret in HttpOnly cookie, never JSON', async () => { mock({ data: { node: { availableForSale: true } } }, { data: { cartCreate: { cart, userErrors: [], warnings: [] } } }); const r = await run({ method: 'POST', body: { action: 'add', merchandiseId: variant.id, quantity: 1 } }); assert.equal(r.code, 200); assert.match(r.headers['Set-Cookie'], /HttpOnly; SameSite=Lax/); assert.ok(!JSON.stringify(r.body).includes('cart-secret')); assert.ok(!JSON.stringify(r.body).includes('checkoutUrl')); });
test('cart cookie survives refresh and uses the complete Shopify ID', async () => { mock({ data: { cart } }); const r = await run({ query: { resource: 'cart' }, headers: cookie }); assert.equal(r.body.cart.totalQuantity, 1); assert.equal(calls[0].body.variables.id, cart.id); });
test('expired cart clears cookie and never silently loses an update', async () => { mock({ data: { cart: null } }); const r = await run({ method: 'POST', headers: cookie, body: { action: 'update', lineId: 'line-1', quantity: 2 } }); assert.equal(r.code, 409); assert.match(r.headers['Set-Cookie'], /Max-Age=0/); });
test('sold-out variants cannot be added', async () => { mock({ data: { node: { availableForSale: false } } }); const r = await run({ method: 'POST', body: { action: 'add', merchandiseId: variant.id, quantity: 1 } }); assert.equal(r.code, 409); assert.equal(calls.length, 1); });
test('rejects invalid quantities before upstream calls', async () => { for (const quantity of [0, -1, 1.2, 100, '2', null]) { const r = await run({ method: 'POST', body: { action: 'add', quantity } }); assert.equal(r.code, 400); } assert.equal(calls.length, 0); });
test('updates and removes existing cart lines', async () => { for (const action of ['update', 'remove']) { mock({ data: { cart } }, { data: { result: { cart, userErrors: [], warnings: [] } } }); const r = await run({ method: 'POST', headers: cookie, body: { action, lineId: 'line-1', quantity: 2 } }); assert.equal(r.code, 200); } });
test('mutation errors are sanitized and warnings are surfaced', async () => { mock({ data: { cart } }, { data: { result: { cart: null, userErrors: [{ message: 'internal-private-test-token' }] } } }); let r = await run({ method: 'POST', headers: cookie, body: { action: 'update', lineId: 'line-1', quantity: 2 } }); assert.equal(r.code, 409); assert.ok(!r.body.error.includes('token')); mock({ data: { cart } }, { data: { result: { cart, userErrors: [], warnings: [{ code: 'MERCHANDISE_OUT_OF_STOCK' }] } } }); r = await run({ method: 'POST', headers: cookie, body: { action: 'update', lineId: 'line-1', quantity: 2 } }); assert.match(r.body.warning, /adjusted/); });
test('checkout is fetched fresh and validates the Shopify hostname', async () => { mock({ data: { cart } }); const r = await run({ method: 'POST', headers: cookie, body: { action: 'checkout' } }); assert.equal(r.body.url, cart.checkoutUrl); assert.equal(safeCheckout('https://evil.example/checkout'), null); assert.equal(safeCheckout('javascript:alert(1)'), null); assert.equal(safeCheckout('https://theprintflowstudio.myshopify.com.evil.test'), null); });
test('missing checkout and unavailable lines block checkout', async () => { for (const changed of [{ ...cart, checkoutUrl: null }, { ...cart, lines: { nodes: [{ merchandise: { availableForSale: false } }] } }]) { mock({ data: { cart: changed } }); const r = await run({ method: 'POST', headers: cookie, body: { action: 'checkout' } }); assert.ok(r.code >= 400); } });
test('cross-origin mutations rejected', async () => { const r = await run({ method: 'POST', headers: { origin: 'https://attacker.example' }, body: { action: 'checkout' } }); assert.equal(r.code, 403); assert.equal(calls.length, 0); });
test('upstream network/GraphQL failures never expose details', async () => { for (const result of [new Error('private-token'), { errors: [{ message: 'private-token' }] }]) { mock(result); const r = await run({ query: { resource: 'products' } }); assert.equal(r.code, 503); assert.ok(!r.body.error.includes('private-token')); } });
test('product metadata is escaped and canonicals use PrintFlow', () => { const html = metadata(product); assert.ok(!html.includes('<script>attack')); assert.match(html, /https:\/\/www.printflowstudio.com\/shop\/test-tee/); assert.match(html, /\\u003c/); assert.match(html, /27.99/); });
